### ISSUE TITLE
Need OS X (Mac) compiled version of nearest_idx3

### ISSUE THREAD

**Issue by mvdm** [mvdm/neuraldata-w16#1]
Currently only has .mexw64 version -- do you have this compiled, @emirvine?

**Comment by emirvine** [comment]
No, I mostly use Windows. Only very recently have I started using a Linux machine that were for MClust and isn't what you need here.

**Comment by mvdm** [comment]
@jcheong0428, could you give compiling this a try when you get a chance? The nearest_idx3.c source file is provided in the codebase.
